import 'package:flutter/material.dart';

const EDITOR_BACKGROUND = Color(0xFF181818);
const ACTIVE_LINE_BACKGROUND = Color(0xFF262626);
const PRIMARY_TEXT_COLOR = Color(0xEBE4E4E4);
const EDITOR_LINE_HEIGHT = 32.0;
const FONT_SIZE = 16.0;
const LINE_NUMBER_TEXT_COLOR = Color(0x42E4E4E4);
const ACTIVE_LINE_NUMBER_TEXT_COLOR = Color(0xEBE4E4E4);
const GUTTER_WIDTH = 64.0;
